# Generated by Django 5.0.6 on 2025-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
