# Generated by Django 5.2 on 2025-05-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_comment_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AddField(
            model_name="post",
            name="login_required",
            field=models.BooleanField(default=False),
        ),
    ]
